### ISSUE TITLE
Change of username

### ISSUE THREAD

**Issue by GregorioSecurity** [SabyasachiRana/WebMap#2]
Because of the change of the GitHub username, from Rev3seSecurity to SabyasachiRana, trying to build from the docker file fails (ie. it's trying to clone a non-existent repo).

**Comment by SabyasachiRana** [comment]
@GregorioSecurity Rev3seSecurity already deleted Webmap, This is a Clone. I'll make a Docker Image for this

**Comment by GregorioSecurity** [comment]
Thanks! I've already fixed it on my end, but there is git clone of the Rev3rseSecurity Repo still in the Dockerfile on line #32

**Comment by SabyasachiRana** [comment]
> Thanks! I've already fixed it on my end, but there is git clone of the Rev3rseSecurity Repo still in the Dockerfile on line #32

Thanks... fixed
