### ISSUE TITLE
Invalid Token

### ISSUE THREAD

**Issue by testdev4** [SabyasachiRana/WebMap#3]
> Generate a new token with:
> docker exec -ti webmap /root/token

1. after docker image build, also need run: chmod +x /opt/nmapdashboard/nmapreport/token.py otherwise /root/token return "Permission denied".
2. After token generation I have still receive error about wrong token.

> root@c0e56bc65d19:~# cat /root/token.sha256 
> 4b1015c1b1f8cd597286a38e692760b86f44a5d8d3d7ae818b2648a1d0f8c7a1root@c0e56bc65d19:~#

**Comment by SabyasachiRana** [comment]
Thanks... I will fix this soon

**Comment by JC-SoCal** [comment]
This error is still occurring.
