### ISSUE TITLE
docker pull failing

### ISSUE THREAD

**Issue by JC-SoCal** [SabyasachiRana/WebMap#5]
running the command: 
`docker pull reborntc/webmap`

results in the following error:
`Error response from daemon: manifest for reborntc/webmap:latest not found: manifest unknown: manifest unknown`

**Comment by SabyasachiRana** [comment]
wait I need to build this in docker hub... I'm doing this already

**Comment by itbuiductai** [comment]
@SabyasachiRana please fix it soon!

**Comment by qazero** [comment]
Any update on this? It still isn't working...

**Comment by marcositu** [comment]
We have uploaded an image of WebMap for those want to use it
https://hub.docker.com/r/marcositu/webmap

**Comment by akshay345345** [comment]
can someone please tell me the meaning of docker pull reborntc/webmap
